name: CI
on:
  pull_request:
  push:
    branches: ['*']

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install stable toolchain
        run: rustup toolchain install stable

      - uses: Swatinem/rust-cache@v2

      - name: Run cargo style check
        run: cargo fmt --all -- --check

      - name: Run cargo test
        run: cargo test --lib

      - name: Run cargo integration test
        run: cargo test -- --test-threads=1
        if: github.ref == 'refs/heads/master'
        env:
          SECRET_SEED: ${{ secrets.SECRET_SEED }}
